# Site settings
title: Munin Monitoring
email: info@munin-monitoring.org
description: >
	Munin is a networked resource monitoring tool that can help analyze
	resource trends and what just happened to kill our performance?
	problems. It is designed to be very plug and play. A default
	installation provides a lot of graphs with almost no work.
url: "http://munin-monitoring.org"

# Force include some files
include:
  - _pages # We put pages in the _pages directory
  - .htaccess

# Build settings
markdown: kramdown
