# Site settings
title: Munin
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://munin-monitoring.org"

# Force include some files
include:
  - _pages # We put pages in the _pages directory
  - .htaccess

# Build settings
markdown: kramdown
